py script renamed

diff --git a/src/rocks-lifemapper/catalogBoomJob.in b/src/rocks-lifemapper/catalogBoomJob.in
--- a/src/rocks-lifemapper/catalogBoomJob.in
+++ b/src/rocks-lifemapper/catalogBoomJob.in
@@ -28,11 +28,8 @@ SetDefaults () {
     SITE_CONFIG_FILE=@LMHOME@/config/config.site.ini
 
     # script
-    SCENCAT_PY=@LMHOME@/LmDbServer/tools/catalogScenPkg.py    
-    TAXCAT_PY=@LMHOME@/LmDbServer/tools/catalogTaxonomy.py    
-    BOOMCAT_PY=@LMHOME@/LmDbServer/tools/catalogBoomJob.py
-    BG_ENCODE_PY=@LMHOME@/LmServer/tools/encodeBioGeoHypotheses.py
-    TREE_ENCODE_PY=@LMHOME@/LmServer/tools/encodeTree.py
+    BOOMCAT_PY=@LMHOME@/LmDbServer/tools/catalogBoomInputs.py
+    BOOMFLOW_PY=@LMHOME@/LmDbServer/tools/catalogWriteBoomMakeflows.py
 
     THISNAME=`/bin/basename $0`
     LOG=@LMSCRATCHDISK@/log/$THISNAME.log
@@ -73,75 +70,8 @@ TimeStamp () {
     echo $1 `/bin/date` >> $LOG
 }
 
-
-### populate lifemapper DB with environmental scenario inputs for default users, no makeflow
-PopulateScenariosForUser () {
-    if [ -f $SCENCAT_PY ] ; then
-        echo "Cataloging env data $SCEN_PKG for user $ARCHIVE_USER with '$SCENCAT_PY' ..." | tee -a $LOG
-        /opt/python/bin/@PYTHONVER@ $SCENCAT_PY  $SCEN_PKG  $ARCHIVE_USER \
-                                         2>&1 | tee -a $LOG
-    else
-        echo "Error: Missing file $SCENCAT_PY" | tee -a $LOG
-        exit 1
-    fi
-}
-
-### create a makeflow to populate lifemapper DB with GBIF Backbone Taxonomy
-# TODO: function should create a makeflow to call $TAXCAT_PY script
-PopulateTaxonomy () {
-    if [ -f $TAXCAT_PY ] ; then
-        echo "Inserting a makeflow to catalog GBIF Taxonomy with $TAXCAT_PY ..." | tee -a $LOG
-        /opt/python/bin/@PYTHONVER@ $TAXCAT_PY  2>&1 | tee -a $LOG
-    else
-        echo "Error: Missing file $TAXCAT_PY" | tee -a $LOG
-        exit 1
-    fi
-}
-
-
-### encode default tree with unique ids to match species data
-# this must be run *AFTER* the taxonomy or species data has been inserted
-# TODO: function should create a makeflow to call $ENCODE_PY script
-EncodeTree () {
-    if [ -f $ENCODE_PY ] ; then
-    	# TREE value is filename with extension
-    	EXT=.nex
-	    trimLen=`expr length $EXT` 
-	    fullLen=`expr length $TREE_BASENAME`
-	    len=`expr $fullLen - $trimLen`
-	    TREENAME=${TREE_BASENAME:0:len}
-
-        echo "*****************"   | tee -a $LOG
-        echo "Encode the $TREE with existing LM species identifiers"   | tee -a $LOG
-        echo "   $ENCODE_PY"  --user=$ARCHIVE_USER  --tree_name=$TREENAME  | tee -a $LOG
-        echo "*****************"   | tee -a $LOG
-        #echo "Running $ENCODE_PY for user tree ..." | tee -a $LOG
-        #/opt/python/bin/@PYTHONVER@ $ENCODE_PY --user=$ARCHIVE_USER --tree_name=$TREENAME 2>&1 | tee -a $LOG
-    else
-        echo "Error: Missing file $ENCODE_PY" | tee -a $LOG
-        exit 1
-    fi
-}
-
-### encode biogeographic hypotheses into matrix for this gridset
-# this must be run *AFTER* the BOOM workflow has been initialized 
-# TODO: function should create a makeflow to call $ENCODE_PY script
-EncodeBioGeo () {
-    if [ -f $ENCODE_PY ] ; then
-        echo "*****************"   | tee -a $LOG
-        echo "Encode the $BIOGEO_HYPOTHESES into matrix for gridset $ARCHIVE_NAME"   | tee -a $LOG
-        echo "   $ENCODE_PY"  --user=$ARCHIVE_USER  --gridset_name=$ARCHIVE_NAME  | tee -a $LOG
-        echo "*****************"   | tee -a $LOG
-        #echo "Running $ENCODE_PY for biogeographic hypotheses ..." | tee -a $LOG
-        #/opt/python/bin/@PYTHONVER@ $ENCODE_PY --user=$ARCHIVE_USER --gridset_name=$ARCHIVE_NAME 2>&1 | tee -a $LOG
-    else
-        echo "Error: Missing file $ENCODE_PY" | tee -a $LOG
-        exit 1
-    fi
-}
-
 ### populate lifemapper DB with inputs for Global PAM and 
-### a makeflow to begin computing the BOOM workflow
+### makeflows to begin computing the BOOM workflow
 PopulateBoomInputs () {
     if [ -f $BOOMCAT_PY ] ; then
         echo "Catalog BOOM $INIT_CONFIG inputs then insert a makeflow to create and run tasks with '$BOOMCAT_PY' ..." | tee -a $LOG
@@ -149,6 +79,17 @@ PopulateBoomInputs () {
                                          2>&1 | tee -a $LOG
     else
         echo "Error: Missing file $BOOMCAT_PY" | tee -a $LOG
+        exit 1
+    fi   
+}
+
+### write and catalog makeflows to begin computing the BOOM workflow
+WriteBoomMakeflows () {
+    if [ -f $BOOMFLOW_PY ] ; then
+        echo "Catalog and write BOOM $INIT_CONFIG makeflows to run tasks with '$BOOMFLOW_PY' ..." | tee -a $LOG
+        /opt/python/bin/@PYTHONVER@ $BOOMFLOW_PY  $INIT_CONFIG  2>&1 | tee -a $LOG
+    else
+        echo "Error: Missing file $BOOMFLOW_PY" | tee -a $LOG
         exit 1
     fi   
 }
@@ -173,6 +114,8 @@ SetDefaults $1
 TimeStamp "# Start"
 
 PopulateBoomInputs
+# TODO: separate Makeflow creation into different script
+#WriteBoomMakeflows
 
 FixPermissions
 TimeStamp "# End"
