handle file permissions cleanly

diff --git a/src/rocks-lifemapper/catalogBoomJob.in b/src/rocks-lifemapper/catalogBoomJob.in
--- a/src/rocks-lifemapper/catalogBoomJob.in
+++ b/src/rocks-lifemapper/catalogBoomJob.in
@@ -26,6 +26,12 @@ fi
 SetDefaults () {
     INIT_CONFIG=$1
 
+    /bin/egrep -i "^lmwriter" /etc/passwd
+    if [ $? -ne 0 ]; then
+        echo "Error: user lmwriter does not exist" | tee -a $LOG
+        exit 1
+    fi
+
     # config files
     CONFIG_FILE=@LMHOME@/config/config.lmserver.ini
     SITE_CONFIG_FILE=@LMHOME@/config/config.site.ini
@@ -72,7 +78,6 @@ SetDefaults () {
     # TODO: get epsg from metadata
     #EPSG=`grep -i epsg $SCEN_PKG_META | awk '{print $2}'`
     EPSG=4326
-    LAYER_DIR=$ARCHIVE_USER_DATA_DIR/$EPSG/Layers 
 }
 
 TimeStamp () {
@@ -83,6 +88,11 @@ TimeStamp () {
 ### makeflows to begin computing the BOOM workflow
 PopulateBoomInputs () {
     if [ -f $BOOMCAT_PY ] ; then
+        LAYER_DIR=$ARCHIVE_USER_DATA_DIR/$EPSG/Layers 
+        MF_DIR=$ARCHIVE_USER_DATA_DIR/makeflow
+         
+    	FixPermissions $LAYER_DIR
+    	FixPermissions $MF_DIR
         echo "Catalogs BOOM $INIT_CONFIG inputs then inserts a makeflow to create and run tasks with '$BOOMCAT_PY' ..." | tee -a $LOG
         /opt/python/bin/@PYTHONVER@ $BOOMCAT_PY  $INIT_CONFIG \
                              			 --init_makeflow=True \
@@ -95,16 +105,14 @@ PopulateBoomInputs () {
 
 
 FixPermissions () {
-    /bin/egrep -i "^lmwriter" /etc/passwd
-    if [ $? -ne 0 ]; then
-        echo "Error: user lmwriter does not exist" | tee -a $LOG
-        exit 1
-    fi
-
+	THIS_DIR=$1
+	
     # This script is run by root, so set group write permission on data dir if default
-    echo "Check lmwriter group permissions on $ARCHIVE_USER_DATA_DIR" | tee -a $LOG
-#     /bin/chgrp -R lmwriter $ARCHIVE_USER_DATA_DIR
-#     /bin/chmod -R g+ws     $ARCHIVE_USER_DATA_DIR
+    echo "Check lmwriter group permissions on $THIS_DIR" | tee -a $LOG
+    if [ -d $THIS_DIR ]; then
+        /bin/chgrp -R lmwriter $THIS_DIR
+        /bin/chmod -R g+ws     $THIS_DIR
+    fi
 }
 
 
diff --git a/src/rocks-lifemapper/getBoomPackageForUser.in b/src/rocks-lifemapper/getBoomPackageForUser.in
--- a/src/rocks-lifemapper/getBoomPackageForUser.in
+++ b/src/rocks-lifemapper/getBoomPackageForUser.in
@@ -37,6 +37,12 @@ set_defaults() {
     THIS_USER=$2
     LMURL=@LMURL@
     THISNAME=`/bin/basename $0`
+    
+    /bin/egrep -i "^lmwriter" /etc/passwd
+    if [ $? -ne 0 ]; then
+        echo "Error: user lmwriter does not exist" | tee -a $LOG
+        exit 1
+    fi    
 
     LOG=@LMSCRATCHDISK@/log/$THISNAME.log
     # Append to existing logfile
@@ -126,6 +132,7 @@ set_user_and_directory () {
     else 
         echo "Create data directory $USER_DIR" | tee -a $LOG
         /bin/mkdir $USER_DIR 
+        fix_permissions $USER_DIR 
     fi
     
     # Set User data filenames
@@ -200,23 +207,24 @@ install_hypotheses_data () {
     fi
 }
 
-### Fix USER_DIR to group lmwriter with write permission 
+### Fix THIS_DIR to group lmwriter with write permission 
 fix_permissions () {
-    /bin/egrep -i "^lmwriter" /etc/passwd
-    if [ $? -ne 0 ]; then
-        echo "Error: user lmwriter does not exist" | tee -a $LOG
-        exit 1
-    fi
+	THIS_DIR=$1
 
-    echo "Set/reset group and write permission on $USER_DIR data dir"   | tee -a $LOG
-    if [ -d $USER_DIR ]; then
-        /bin/chgrp -R lmwriter $USER_DIR
-        /bin/chmod -R g+ws     $USER_DIR
-    fi
-    
+    echo "Set/reset group and write permission on $THIS_DIR data dir"   | tee -a $LOG
+    if [ -d $THIS_DIR ]; then
+        /bin/chgrp -R lmwriter $THIS_DIR
+        /bin/chmod -R g+ws     $THIS_DIR
+    fi    
+}
+
+
+### Remove temporary package contents file 
+cleanup () {
     echo "Cleanup files in $TEMP_DIR"   | tee -a $LOG
     rm -f $BOOM_CONTENTS_FILE
 }
+
 
 findget_scen_data () {
     if [ -f $SCEN_META_FILE ]; then
@@ -279,7 +287,7 @@ install_param_file
 install_occ_data
 install_tree_data
 install_hypotheses_data
-fix_permissions
 instruct_user
+cleanup
 
 TimeStamp "# End"
