fix db create or update on roll install

diff --git a/src/rocks-lifemapper/fillDB.in b/src/rocks-lifemapper/fillDB.in
--- a/src/rocks-lifemapper/fillDB.in
+++ b/src/rocks-lifemapper/fillDB.in
@@ -37,7 +37,8 @@ SetDefaults () {
     USER=admin
     # file to get password from
     USERSFILE=@PKGROOT@/rocks/etc/users
-    DEFINESQL=@LMHOME@/LmDbServer/dbsetup/runAllSQLScripts.sql
+    DEFINE_TABLES_SQL=@LMHOME@/LmDbServer/dbsetup/defineDBTables.sql
+    ADD_FUNCTIONS_SQL=@LMHOME@/LmDbServer/dbsetup/addDBFunctions.sql
     POPULATEPY=@LMHOME@/LmDbServer/tools/initCatalog.py
     TAXONOMYPY=@LMHOME@/LmDbServer/tools/readTaxonomy.py
     COMPUTEPY=@LMHOME@/LmDbServer/tools/registerCompute.py
@@ -45,6 +46,13 @@ SetDefaults () {
     LOG=/tmp/`/bin/basename $0`.log
     touch $LOG
     TimeStamp "# Start"
+
+    if [ -d /var/lib/pgsql/@PGSQLVER@/data ]; then
+       echo "postgres db exists" >> $LOG
+	    EXISTING_DB=true
+	 else
+	    EXISTING_DB=false
+    fi
 }
 
 TimeStamp () {
@@ -75,11 +83,22 @@ SetPass () {
 
 ### define databases 
 Define () {
-    if [ -f $DEFINESQL ] ; then
-        echo "Running $DEFINESQL ..." | tee -a $LOG
-        psql -U admin -d template1 -f $DEFINESQL 2>&1 | tee -a $LOG
+    if [ -f $DEFINE_TABLES_SQL ] ; then
+        echo "Running $DEFINE_TABLES_SQL ..." | tee -a $LOG
+        psql -U admin -d template1 -f $DEFINE_TABLES_SQL 2>&1 | tee -a $LOG
     else
-        echo "Error: missing file $DEFINESQL" | tee -a $LOG
+        echo "Error: missing file $DEFINE_TABLES_SQL" | tee -a $LOG
+        exit 1
+    fi
+}
+
+### add database views, types, functions 
+AddFunctions () {
+    if [ -f $ADD_FUNCTIONS_SQL ] ; then
+        echo "Running $ADD_FUNCTIONS_SQL ..." | tee -a $LOG
+        psql -U admin -d template1 -f $ADD_FUNCTIONS_SQL 2>&1 | tee -a $LOG
+    else
+        echo "Error: missing file $ADD_FUNCTIONS_SQL" | tee -a $LOG
         exit 1
     fi
 }
@@ -126,7 +145,10 @@ fi
 SetDefaults
 SetPermissions
 SetPass
-Define
+if [ ! $EXISTING_DB ] ; then
+    Define
+fi
+AddFunctions
 Populate
 AddTaxonomy
 RegisterCompute
