fix permissions on newly created user data dir; update rpm release

diff --git a/src/rocks-lifemapper/fillDB.in b/src/rocks-lifemapper/fillDB.in
--- a/src/rocks-lifemapper/fillDB.in
+++ b/src/rocks-lifemapper/fillDB.in
@@ -2,80 +2,56 @@
 
 # Purpose: define and populate lifemapper pipeline
 #
-# This scirpt is run by a superuser, it reads the @PKGROOT@/rocks/etc/users file
-# to get the password for the "admin" DB user and runs psql to execute all the sql scripts
+# This script is run by a superuser
 
 usage () 
 {
     echo "Usage: $0"
     echo "This script is run by the superuser. It will "
-    echo "     - run runAllSQLScripts.sql to define the databases "
     echo "     - run initCatalog.py to populate the databases and init taxonomy"
     echo "     - run readTaxonomy.py to add taxonomy"
+    echo "     - run registerCompute.py to register a compute node"
     echo "   "
     echo "The output of the script is in /tmp/`/bin/basename $0`.log"
 }
 
-SetPermissions () {
-   /bin/egrep -i "^lmwriter" /etc/passwd
-   if [ $? -eq 0 ]; then
-       echo "Update group permissions for lmwriter on @LMHOME@" | tee -a $LOG
-       for item in "config" "Lm*" "__init__.py*" ; do
-           /bin/chgrp -R lmwriter @LMHOME@/$item
-           /bin/chmod -R g+ws @LMHOME@/$item
-       done
-   else
-        echo "Error: user lmwriter does not exist" | tee -a $LOG
-        exit 1
-   fi
-
-}
-
 ### define varibles
 SetDefaults () {
-    # db user
-    USER=admin
-    # file to get password from
-    USERSFILE=@PKGROOT@/rocks/etc/users
+    # scripts
     POPULATEPY=@LMHOME@/LmDbServer/tools/initCatalog.py
     TAXONOMYPY=@LMHOME@/LmDbServer/tools/readTaxonomy.py
     COMPUTEPY=@LMHOME@/LmDbServer/tools/registerCompute.py
 
+	 # config files
+    CONFIG_FILE=@LMHOME@/config/config.lmserver.ini
+    SITE_CONFIG_FILE=@LMHOME@/config/site.ini
+    
+    # get the DATASOURCE  and ARCHIVE_USER values 
+    # from site.ini or config.lmserver.ini file
+    echo "Looking for DATASOURCE"   | tee -a $LOG  
+    DATASOURCE=`grep DATASOURCE $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+    if [ ! "$DATASOURCE" ] ; then 
+        DATASOURCE=`grep DATASOURCE $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+    fi
+    
+    echo "Looking for $ARCHIVE_USER"   | tee -a $LOG  
+    ARCHIVE_USER=`grep ARCHIVE_USER $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+    if [ ! "$ARCHIVE_USER" ] ; then 
+        ARCHIVE_USER=`grep ARCHIVE_USER $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+    fi
+    ARCHIVE_USER_DATA_DIR=@DATADIR_SERVER@/archive/$ARCHIVE_USER
+    if [ ! -d $ARCHIVE_USER_DATA_DIR ] ; then
+       IS_NEW_USER_DIR=true
+    else
+       IS_NEW_USER_DIR=false
+    fi
+    
     LOG=/tmp/`/bin/basename $0`.log
     touch $LOG
-
-    if [ -d /var/lib/pgsql/@PGSQLVER@/data ]; then
-       echo "postgres db exists" >> $LOG
-	    EXISTING_DB=true
-	 else
-	    EXISTING_DB=false
-    fi
 }
 
 TimeStamp () {
     echo $1 `/bin/date` >> $LOG
-}
-
-### sets the password for db "admin" user to execute sql commands
-SetPass () {
-
-    # check if users file exists
-    if [ ! -f $USERSFILE ] ; then
-        echo "Error: missing file $USERSFILE" | tee -a $LOG
-        exit 1
-    fi
-
-    # check who is running the scipt
-    cat $USERSFILE > /dev/null
-    RETVAL=$?
-    if [ $RETVAL -ne 0 ]; then
-        echo "Error: You must be root to run this script"  | tee -a $LOG
-        exit 1
-    fi
-
-    # get the password from 'users' file
-    PASS=`grep admin $USERSFILE | awk '{print $2}'`
-    export PGPASSWORD=$PASS
 }
 
 ### populate lifemapper DB
@@ -89,15 +65,24 @@ Populate () {
     fi
 }
 
-### read and populate taxonomy table
-AddTaxonomy () {
-    # get the DATASOURCE value from site.ini or config.lmserver.ini file
-    echo "Looking for DATASOURCE"   | tee -a $LOG  
-    DATASOURCE=`grep DATASOURCE $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    if [ ! "$DATASOURCE" ] ; then 
-        DATASOURCE=`grep DATASOURCE $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+FixPermissions () {
+    /bin/egrep -i "^lmwriter" /etc/passwd
+    if [ $? -ne 0 ]; then
+        echo "Error: user lmwriter does not exist" | tee -a $LOG
+        exit 1
     fi
 
+    # This script is run by root, so set group write permission on new data dir
+    echo "Create and set group write permission on new $ARCHIVE_USER data dir"   | tee -a $LOG
+    if [ $IS_NEW_USER_DIR ] ; then
+       echo "Update lmwriter group permissions on $ARCHIVE_USER_DATA_DIR" | tee -a $LOG
+       /bin/chown -R lmwriter:lmwriter $ARCHIVE_USER_DATA_DIR
+       /bin/chmod -R g+ws $ARCHIVE_USER_DATA_DIR
+    fi
+}
+
+### read and populate taxonomy table
+AddTaxonomy () {
     if [ $DATASOURCE = "GBIF" ] ; then
         echo "Running $TAXONOMYPY ..." | tee -a $LOG
         /opt/python/bin/@PYTHONVER@ $TAXONOMYPY 2>&1 | tee -a $LOG
@@ -126,8 +111,7 @@ fi
 
 SetDefaults
 TimeStamp "# Start"
-SetPermissions
-SetPass
 Populate
+FixPermissions
 RegisterCompute
 TimeStamp "# End"
