get user/datasource from provided ini file

diff --git a/src/rocks-lifemapper/fillDB.in b/src/rocks-lifemapper/fillDB.in
--- a/src/rocks-lifemapper/fillDB.in
+++ b/src/rocks-lifemapper/fillDB.in
@@ -21,38 +21,63 @@ SetDefaults () {
     else
         INIT_CONFIG=$1
     fi
-    THISNAME=`/bin/basename $0`
-
-    # scripts
-    BORG_POPULATEPY=@LMHOME@/LmDbServer/boom/initboom.py
 
     # config files
     CONFIG_FILE=@LMHOME@/config/config.lmserver.ini
     SITE_CONFIG_FILE=@LMHOME@/config/config.site.ini
-    
-    if [ -f $SITE_CONFIG_FILE ] ; then        
-        # get the DATASOURCE  and ARCHIVE_USER values 
-        # from config.site.ini or config.lmserver.ini file
-        echo "Looking for DATASOURCE and ARCHIVE_USER in site config file"   | tee -a $LOG  
-        DATASOURCE=`grep DATASOURCE $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-        ARCHIVE_USER=`grep ARCHIVE_USER $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    fi
 
-    if [ ! "$DATASOURCE" ] ; then 
-        echo "Looking for DATASOURCE in installed config file"   | tee -a $LOG  
-        DATASOURCE=`grep DATASOURCE $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    fi
-    
-    if [ ! "$ARCHIVE_USER" ] ; then 
-        echo "Looking for ARCHIVE_USER in installed config file"   | tee -a $LOG  
-        ARCHIVE_USER=`grep ARCHIVE_USER $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    fi
-    
-    ARCHIVE_USER_DATA_DIR=@DATADIR_SHARED@/archive/$ARCHIVE_USER
-    
+    # script
+    BORG_POPULATEPY=@LMHOME@/LmDbServer/boom/initboom.py    
+
+    THISNAME=`/bin/basename $0`
     LOG=@LMSCRATCHDISK@/log/$THISNAME.log
     rm -f $LOG
     touch $LOG
+
+    if [ -f $INIT_CONFIG ] ; then
+        echo "Looking for DATASOURCE and ARCHIVE_USER in user config file $INIT_CONFIG"   | tee -a $LOG  
+        DATASOURCE=`grep DATASOURCE $INIT_CONFIG | grep -v ';' | awk '{print $2}'`
+        ARCHIVE_USER=`grep ARCHIVE_USER $INIT_CONFIG | grep -v ';' | awk '{print $2}'`
+    fi
+
+    if [ ! "$DATASOURCE" ] ; then 
+        # look in config.site.ini
+        if [ -f $SITE_CONFIG_FILE ] ; then        
+            echo "Looking for DATASOURCE in site config file"   | tee -a $LOG  
+            DATASOURCE=`grep DATASOURCE $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+        fi
+        
+        # look in installed config file        
+        if [ ! "$DATASOURCE" ] ; then 
+            echo "Looking for DATASOURCE in installed config file"   | tee -a $LOG  
+            DATASOURCE=`grep DATASOURCE $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+        fi
+    fi
+    
+    if [ ! "$ARCHIVE_USER" ] ; then 
+        # look in config.site.ini
+        if [ -f $SITE_CONFIG_FILE ] ; then        
+            echo "Looking for ARCHIVE_USER in site config file"   | tee -a $LOG  
+            ARCHIVE_USER=`grep ARCHIVE_USER $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+        fi
+        
+        # look in installed config file        
+        if [ ! "$ARCHIVE_USER" ] ; then 
+            echo "Looking for ARCHIVE_USER in installed config file"   | tee -a $LOG  
+            ARCHIVE_USER=`grep ARCHIVE_USER $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
+        fi
+    fi
+    
+    if [ ! "$ARCHIVE_USER" ] ; then
+        echo "Error: Missing value for ARCHIVE_USER" | tee -a $LOG
+        exit 1
+    fi
+    if [ ! "$DATASOURCE" ] ; then
+        echo "Error: Missing value for DATASOURCE" | tee -a $LOG
+        exit 1
+    fi
+
+    ARCHIVE_USER_DATA_DIR=@DATADIR_SHARED@/archive/$ARCHIVE_USER    
 }
 
 TimeStamp () {
