separate get/install envpackage from boom data and params

diff --git a/src/rocks-lifemapper/getBoomPackage.in b/src/rocks-lifemapper/getBoomPackage.in
--- a/src/rocks-lifemapper/getBoomPackage.in
+++ b/src/rocks-lifemapper/getBoomPackage.in
@@ -36,7 +36,6 @@ set_defaults() {
     touch $LOG
     
     TEMP_DIR=@LMSCRATCHDISK@/temp
-    CLIMATE_DIR=@DATADIR_SHARED@/@ENV_DATA_DIR@
 
     # *_PKG variables are file basenames, no path or file extension
     BOOM_PKG=$1
@@ -68,11 +67,9 @@ pull_boom_package () {
 ### Read data file names from test package metadata
 read_boom_datanames () {
     # Required data
-    SCEN_PKG=`grep -i ENVIRONMENTAL_PACKAGE $BOOM_META_FILE | grep -v ';' | awk '{print $2}'`
     BOOM_PARAM_BASENAME=`grep -i BOOM_PARAMETER_FILE $BOOM_META_FILE | grep -v ';' | awk '{print $2}'`
 
-    echo "Var SCEN_PKG = $SCEN_PKG" | tee -a $LOG
-    echo "    BOOM_PARAM_BASENAME = $BOOM_PARAM_BASENAME" | tee -a $LOG       
+    echo "Var BOOM_PARAM_BASENAME = $BOOM_PARAM_BASENAME" | tee -a $LOG       
 
     # Optional data
     POINT_PKG=`grep -i SPECIES_PACKAGE $BOOM_META_FILE | grep -v ';' | awk '{print $2}'`
@@ -83,8 +80,10 @@ read_boom_datanames () {
     echo "    TREE_BASENAME = $TREE_BASENAME" | tee -a $LOG       
     echo "    BIOGEO_PKG = $BIOGEO_PKG" | tee -a $LOG
 
-    CLIMATE_META_FILE=$CLIMATE_DIR/$SCEN_PKG.py        
     BOOM_PARAM_FILE=$TEMP_DIR/$BOOM_PARAM_BASENAME
+    SCEN_PKG=`grep -i SCENARIO_PACKAGE $BOOM_PARAM_FILE | grep -v ';' | awk '{print $2}'`
+    SCEN_DIR=@DATADIR_SHARED@/@ENV_DATA_DIR@
+    SCEN_META_FILE=$SCEN_DIR/$SCEN_PKG.py
 }
 
 ### Retrieve ARCHIVE_USER from BOOM parameter file package 
@@ -113,7 +112,22 @@ get_user_create_dir () {
     POINT_META_FILE=$USER_DIR/$POINT_PKG.meta
 }
 
-### Move (optional) climate data named in POINT_PKG (bison pulls dynamically)
+### Move species data named in POINT_PKG (bison pulls dynamically)
+install_param_file () {
+    # find parameter file
+    BOOM_PARAM_FILE=$TEMP_DIR/$BOOM_PARAM_BASENAME
+    echo "Move boom parameter file into $USER_DIR" | tee -a $LOG
+    if [ -f $BOOM_PARAM_FILE ]; then
+        cp -p $BOOM_PARAM_FILE $USER_DIR/
+        rm -f $BOOM_PARAM_FILE
+
+    else
+        echo "Failed to find $BOOM_PARAM_FILE ..." | tee -a $LOG
+        exit 1
+    fi
+}
+
+### Move species data named in POINT_PKG (bison pulls dynamically)
 install_occ_data () {
     # find metadata file pkgname.py
     if [ -z ${POINT_PKG} ]; then
@@ -133,28 +147,14 @@ install_occ_data () {
     fi
 }
 
-### Move occurrence data named in SCENARIO_PACKAGE
-install_climate_data () {
-    # find metadata file pkgname.py
-    if [ -f $CLIMATE_META_FILE ]; then
-        echo "Climate metadata $CLIMATE_META_FILE already present" | tee -a $LOG
-    # uncompress 
-    elif [ -f $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ ]; then
-        echo "Uncompress climate data into $CLIMATE_DIR" | tee -a $LOG
-        tar xzf $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ -C $CLIMATE_DIR/
-    else
-        echo "Failed to retrieve $SCEN_PKG ..." | tee -a $LOG
-        exit 1
-    fi
-}
 
-### Move optional tree and biogeographic hypotheses data named in TREE_BASENAME and BIOGEO_PKG
-install_optional_data () {
+### Move optional tree named in TREE_BASENAME to user dir
+install_tree_data () {
     # if tree file exists, move to User dir
     if [ -z ${TREE_BASENAME} ]; then
         echo "No tree data" | tee -a $LOG
     else
-        echo "Copy tree data into $USER_DIR" | tee -a $LOG
+        echo "Move tree data into $USER_DIR" | tee -a $LOG
         if [ -f $TEMP_DIR/$TREE_BASENAME ]; then
             cp -p $TEMP_DIR/$TREE_BASENAME $USER_DIR/
             rm -f $TEMP_DIR/$TREE_BASENAME
@@ -162,6 +162,10 @@ install_optional_data () {
             echo "Failed to find $TREE_BASENAME ..." | tee -a $LOG
         fi
     fi
+}
+
+### Move optional biogeographic hypotheses named in BIOGEO_PKG to User dir
+install_hypotheses_data () {
     # if biogeographic hypotheses package exists, move to User dir
     if [ -z ${BIOGEO_PKG} ]; then
         echo "No biogeographic hypotheses" | tee -a $LOG
@@ -184,11 +188,6 @@ fix_permissions () {
         exit 1
     fi
 
-    # This script is run by root, so set group write permission on new data dir
-    echo "Reset group and write permission on $CLIMATE_DIR data dir"   | tee -a $LOG
-    /bin/chgrp -R lmwriter $CLIMATE_DIR
-    /bin/chmod -R g+ws     $CLIMATE_DIR
-
     echo "Set/reset group and write permission on $USER_DIR data dir"   | tee -a $LOG
     if [ -d $USER_DIR ]; then
         /bin/chgrp -R lmwriter $USER_DIR
@@ -208,14 +207,14 @@ instruct_user () {
     echo ""   | tee -a $LOG
     echo ""   | tee -a $LOG
     echo ""   | tee -a $LOG
-    echo "*****************"   | tee -a $LOG
-    echo "To transform climate layers, run:"   | tee -a $LOG
-    echo "@LMHOME@/rocks/bin/transformData $SCEN_PKG"   | tee -a $LOG
-    echo "*****************"   | tee -a $LOG
     echo ""   | tee -a $LOG
+
     echo "*****************"   | tee -a $LOG
-    echo "To catalog input data for BOOM computations, run:"   | tee -a $LOG
-    echo "@LMHOME@/rocks/bin/fillDB $BOOM_PARAM_FILE"   | tee -a $LOG
+    echo "Make sure the $SCEN_PKG data and $SCEN_META_FILE metadata are present"    | tee -a $LOG
+    echo "   if not, run"    | tee -a $LOG
+    echo "   @LMHOME@/rocks/bin/getScenPackageForUser $SCEN_PKG $BOOM_USER"   | tee -a $LOG
+    echo "then catalog input data for BOOM computations with"   | tee -a $LOG
+    echo "   @LMHOME@/rocks/bin/fillDB $BOOM_PARAM_FILE"   | tee -a $LOG
     echo "*****************"   | tee -a $LOG
 }
 
@@ -230,9 +229,10 @@ TimeStamp "# Start"
 pull_boom_package
 read_boom_datanames
 get_user_create_dir
+install_param_file
 install_occ_data
-install_climate_data
-install_optional_data
+install_tree_data
+install_hypotheses_data
 fix_permissions
 instruct_user
 
