script to download and install testing data

diff --git a/src/rocks-lifemapper/getTestPackage.in b/src/rocks-lifemapper/getTestPackage.in
--- a/src/rocks-lifemapper/getTestPackage.in
+++ b/src/rocks-lifemapper/getTestPackage.in
@@ -27,7 +27,6 @@ if [ $# -ne 1 ]; then
 fi 
 
 set_defaults() {
-    TEST_PKG=$1
     LMURL=@LMURL@
     THISNAME=`/bin/basename $0`
 
@@ -37,19 +36,20 @@ set_defaults() {
     
     TEMP_DIR=@LMSCRATCHDISK@/temp
     CLIMATE_DIR=@DATADIR_SHARED@/@ENV_DATA_DIR@
-    
+
+	 # *_PKG variables are file basenames, no path or file extension
+    TEST_PKG=$1
     TEST_PKG_FILE=$TEMP_DIR/$TEST_PKG.@TARBALL_POSTFIX@
-    TEST_META_FILE=$TEMP_DIR/$TEST_PKG.ini
+    TEST_META_FILE=$TEMP_DIR/$TEST_PKG.ini    
 
-	 # These variables are file basenames, no path or file extension
     SCEN_PKG=`grep -i SCENARIO_PACKAGE $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
-    POINT_PKG=`grep -i SPECIES_OCCURRENCE_PACKAGE $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
-    BOOM_PARAMS=`grep -i BOOM_PARAMS $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
-
-	 BOOM_PARAMS_FILE=$TEMP_DIR/$TEST_META_FILE.ini
     CLIMATE_META_FILE=$CLIMATE_DIR/$SCEN_PKG.py
-    CLIMATE_PKG_FILE=$CLIMATE_DIR/$SCEN_PKG.@TARBALL_POSTFIX@
-    NEW_CLIMATE_DATA_DIR=$CLIMATE_DIR/$SCEN_PKG
+    
+    POINT_PKG=`grep -i SPECIES_OCCURRENCE_PACKAGE $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
+    
+	 # *_PKG variables are file basenames, no path or file extension
+    BOOM_PARAM_BASENAME=`grep -i BOOM_PARAM_FILE $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
+	 BOOM_PARAM_FILE=$TEMP_DIR/$BOOM_PARAM_BASENAME
 }
 
 
@@ -67,34 +67,63 @@ pull_test_package () {
             tar xzf $TEST_PKG_FILE -C $TEMP_DIR/
             rm -f $TEST_PKG_FILE 
         else
-            echo "Failed to retrieve $TEST_PKG ..." | tee -a $LOG
+            echo "Failed to retrieve $TEST_PKG_FILE ..." | tee -a $LOG
         fi
     fi
-
-	 # Get the test Boom user name
-    if [ -f $TEST_META_FILE ]; then
-        echo "Test metadata $TEST_META_FILE already present" | tee -a $LOG
-        BOOM_USER=`grep -i ARCHIVE_USER $BOOM_PARAMS_FILE | grep -v ';' | awk '{print $2}'`
-    else 
-        echo "Failed to retrieve $TEST_PKG" | tee -a $LOG
-        exit(0)
-    fi
-   
 }
 
-### Retrieve climate data named in SCENARIO_PACKAGE
-move_climate_data () {
+### Retrieve ARCHIVE_USER from BOOM parameter file package 
+get_user_create_dir () {
+	 # Get the test Boom user name
+    if [ -f $BOOM_PARAMS_FILE ]; then
+        echo "Find ARCHIVE_USER for BOOM in $BOOM_PARAMS_FILE" | tee -a $LOG
+        BOOM_USER=`grep -i ARCHIVE_USER $BOOM_PARAMS_FILE | grep -v ';' | awk '{print $2}'`
+        USER_DIR=@DATADIR_SHARED@/archive/$BOOM_USER
+    else 
+        echo "Failed to find $BOOM_PARAMS_FILE" | tee -a $LOG
+        exit(0)
+    fi
+
+	 # Find or create the test Boom data directory
+    if [ -d $USER_DIR ]; then
+        echo "ARCHIVE_USER data directory $USER_DIR already exists" | tee -a $LOG
+    else 
+        echo "Create data directory $USER_DIR" | tee -a $LOG
+        /bin/mkdir $USER_DIR 
+    fi
+    
+    # Set User data filenames
+    POINT_META_FILE=$USER_DIR/$POINT_PKG.meta
+}
+
+### Move climate data named in POINT_PKG
+install_occ_data () {
+    # find metadata file pkgname.py
+    if [ -f $POINT_META_FILE ]; then
+        echo "Point metadata $POINT_META_FILE already present" | tee -a $LOG
+    else  
+        # uncompress 
+        if [ -f $TEMP_DIR/$POINT_PKG.@TARBALL_POSTFIX@ ]; then
+            echo "Uncompress point data into $USER_DIR" | tee -a $LOG
+            tar xzf $TEMP_DIR/$POINT_PKG.@TARBALL_POSTFIX@ -C $USER_DIR/
+            rm -f $TEMP_DIR/$POINT_PKG.@TARBALL_POSTFIX@ 
+        else
+            echo "Failed to find $POINT_PKG ..." | tee -a $LOG
+        fi
+    fi
+}
+
+### Move occurrence data named in SCENARIO_PACKAGE
+install_climate_data () {
     # find metadata file pkgname.py
     if [ -f $CLIMATE_META_FILE ]; then
         echo "Climate metadata $CLIMATE_META_FILE already present" | tee -a $LOG
     else  
-        echo "Move climate data into $CLIMATE_DIR" | tee -a $LOG
-        /bin/mv $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ $CLIMATE_PKG_FILE
-  
         # uncompress 
-        if [ -f $CLIMATE_PKG_FILE ]; then
-            tar xzf $CLIMATE_PKG_FILE -C $CLIMATE_DIR/
-            rm -f $CLIMATE_PKG_FILE 
+        if [ -f $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ ]; then
+            echo "Uncompress climate data into $CLIMATE_DIR" | tee -a $LOG
+            tar xzf $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ -C $CLIMATE_DIR/
+            rm -f $TEMP_DIR/$SCEN_PKG.@TARBALL_POSTFIX@
         else
             echo "Failed to retrieve $SCEN_PKG ..." | tee -a $LOG
         fi
@@ -103,8 +132,7 @@ move_climate_data () {
 
 fix_permissions () {
     /bin/egrep -i "^lmwriter" /etc/passwd
-    if [ $? -ne 0 ]; thenCURRENCE_PACKAGE $TEST_META_FILE | grep -v ';' | awk '{print $2}'`
-    BOOM_PARAMS=`grep -i BOOM_PARAMS 
+    if [ $? -ne 0 ]; then
         echo "Error: user lmwriter does not exist" | tee -a $LOG
         exit 1
     fi
@@ -113,6 +141,12 @@ fix_permissions () {
     echo "Reset group and write permission on $CLIMATE_DIR data dir"   | tee -a $LOG
     /bin/chgrp -R lmwriter $CLIMATE_DIR
     /bin/chmod -R g+ws     $CLIMATE_DIR
+
+    echo "Set/reset group and write permission on $USER_DIR data dir"   | tee -a $LOG
+    if [ -d $USER_DIR ]; then
+        /bin/chgrp -R lmwriter $USER_DIR
+        /bin/chmod -R g+ws     $USER_DIR
+    fi
 }
 
 
@@ -122,9 +156,6 @@ instruct_user () {
 
     echo "To initialize BOOM for Boom user, run:"   | tee -a $LOG
     echo "@LMHOME@/rocks/bin/fillDB $BOOM_PARAMS"   | tee -a $LOG
-
-    echo "Then move Point data to /@DATADIR_SHARED@/archive/$BOOM_USER:"   | tee -a $LOG
-    echo "mv $POINT_PACKAGE /@DATADIR_SHARED@/archive/$BOOM_USER"   | tee -a $LOG
 }
 
 TimeStamp () {
@@ -136,7 +167,9 @@ set_defaults $1
 TimeStamp "# Start"
 
 pull_test_package
-move_climate_data
+get_user_create_dir
+install_occ_data
+install_climate_data
 fix_permissions
 instruct_user
 
