update group permissions on /opt/lifemapper/* need for reinstall of lifemapper-server rpm

diff --git a/src/rocks-lifemapper/initDB.in b/src/rocks-lifemapper/initDB.in
--- a/src/rocks-lifemapper/initDB.in
+++ b/src/rocks-lifemapper/initDB.in
@@ -16,6 +16,21 @@ usage ()
     echo "The output of the script is in /tmp/`/bin/basename $0`.log"
 }
 
+SetPermissions () {
+   /bin/egrep -i "^lmwriter" /etc/passwd
+   if [ $? -eq 0 ]; then
+       echo "Update group permissions for lmwriter on /opt/lifemapper/" | tee -a $LOG
+       for item in "config" "Lm*" "__init__.py*" ; do
+           /bin/chgrp -R lmwriter /opt/lifemapper/$item
+           /bin/chmod -R g+ws /opt/lifemapper/$item
+       done
+   else
+        echo "Error: user lmwriter does not exist" | tee -a $LOG
+        exit 1
+   fi
+
+}
+
 ### define varibles
 SetDefaults () {
     # db user
@@ -108,6 +123,7 @@ if [ $# -ne 0 ]; then
 fi 
 
 SetDefaults
+SetPermissions
 SetPass
 Define
 Populate
